[package]
name = "blob"
version = "0.1.0"

[dependencies]
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti.git" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
