name: CI
on:
  push:
  merge_group:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.5.3"
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.17.1
      - run: cd contracts && scarb fmt --check
      - run: cd contracts && snforge test